<?php
namespace Andrewlamers\LaravelAdvancedConsole\Database\Migrations;

use Andrewlamers\LaravelAdvancedConsole\Facades\CommandConfig;

class Migration extends \Illuminate\Database\Migrations\Migration {
    public function getConnection()
    {
        return CommandConfig::getConnection(); // TODO: Change the autogenerated stub
    }
}